services:
  dodoc-node:
    image: ghcr.io/l-atelier-des-chercheurs/slashdoc:latest
    ports:
      - "8080:8080"
    volumes:
      - slashdoc-data:/home/node/Documents/slashdoc
    restart: always

volumes:
  slashdoc-data:
